import { CarInterface } from "../models/interface";

export const CARS:CarInterface[] = [
  {
    id:1,
    marque: 'Tesla',
    modele: 'Model S',
    images: "/images/tesla.png",
    annee: 2023,
    couleur: 'Bleu',
    svg:"/svg/electric.svg",
    type: 'Electrique',
    prix: 120000,
    options: ['Autopilot', 'Toit panoramique', 'Sièges chauffants'],
  },
  {
    id:2,
    marque: 'Porsche',
    modele: '911 Carrera',
    images: "/images/porche.png",
    annee: 2022,
    couleur: 'Rouge',
    svg:"/svg/essence.svg",
    type: 'Essence',
    prix: 150000,
    options: ['Pack Sport Chrono', 'Échappement sport', 'Sièges en cuir'],
  },
  {
    id:3,
    marque: 'Toyota',
    modele: 'Corolla',
    images: "/images/toyota.png",
    annee: 2021,
    couleur: 'Gris',
    svg:"/svg/hybrid.svg",
    type: 'Hybride',
    prix: 30000,
    options: ['Caméra de recul', 'Régulateur de vitesse adaptatif', 'Système de navigation'],
  },
  {
    id:4,
    marque: 'Ford',
    modele: 'Mustang',
    images: "/images/ford.png",
    annee: 2020,
    couleur: 'Noir',
    svg:"/svg/essence.svg",
    type: 'Essence',
    prix: 45000,
    options: ['Sièges en cuir', 'Système audio premium', 'Jantes en alliage'],
  },
  {
    id:5,
    marque: 'Renault',
    modele: 'Clio',
    images: "/images/renault.png",
    annee: 2023,
    couleur: 'Blanc',
    svg:"/svg/essence.svg",
    type: 'Essence',
    prix: 25000,
    options: ['Aide au stationnement', 'Climatisation automatique', 'Ecran tactile'],
  },
];